---
title: "Bayes Methods"
author: "Bryana A.S. Thieret"
format: pdf
---


```{r warning=FALSE, output=FALSE}
library(tidyverse)
library(readxl)

############################################################

Comasco2015 = tibble::tibble(
  "Week" = c(1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6),
  "Group" = c("AFR", "AFR", "AFR", "AFR", "AFR", "AFR", "MS15", "MS15", "MS15", "MS15", "MS15", "MS15", "MS360", "MS360", "MS360", "MS360", "MS360", "MS360"),
  "Ethanol_Percentage" = c(5, 5, 20, 20, 20, 20, 5, 5, 20, 20, 20, 20, 5, 5, 20, 20, 20, 20),
  "Access_Hours" = c(24, 2, 2, 2, 2, 2, 24, 2, 2, 2, 2, 2, 24, 2, 2, 2, 2, 2),
  "Median" = c(1.61, 0.40, 1.10, 1.21, 1.37, 1.18, 1.89, 0.67, 1.12, 1.49, 1.23, 1.32, 1.53, 0.57, 1.20, 1.11, 1.28, 1.32),
  "a" = c(0.29, 0.18, 0.50, 0.59, 0.77, 0.62, 0.87, 0.32, 0.75, 0.89, 1.05, 0.39, 0.21, 0.09, 0.29, 0.56, 0.38, 0.60),
  "b" = c(4.16, 0.75, 2.11, 1.42, 2.08, 1.66, 3.40, 0.99, 1.61, 2.13, 1.74, 1.77, 3.28, 1.14, 1.98, 2.15, 2.52, 2.05),
  "n" = c(11, 11, 11, 11, 11, 11, 10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 20),
  "Sessions" = c(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3))
Comasco2015 = Comasco2015 |>
  mutate(
    Estimated_Mean = (a+2*Median+b)/(4),
    Estimated_SD = ((b - a)/(2 * qnorm((n-0.375)/(n+0.25)))),
    Estimated_Variance = (Estimated_SD)^2
  )

############################################################

GN2006 <- read_excel("G&N2006.xlsx")
GN2006 = GN2006 |> group_by(Phase, Group) |> summarise(mean = mean(Ethanol_Intake),
                                              sd = sd(Ethanol_Intake),
                                              variance = var(Ethanol_Intake))

############################################################
P2003 <- read_excel("P2003.xlsx")

Sessions = tibble::tibble(Ethanol_Percentage = c(2, 4, 6, 8),
               Sessions = c(4, 4, 7, 11),
               n = c(8, 8, 8, 8))

P2003 = left_join(P2003, Sessions, by = "Ethanol_Percentage")

P2003 = P2003 |> mutate(SD = SEM*sqrt(n),
                        variance = SD^2)

############################################################

O2011 <- read_excel("O2011.xlsx")
O2011 = O2011 |> pivot_wider(names_from = Summary_Statistics, values_from = Values)

# estimated mean and SD from Wan et al., 2014
O2011 = O2011 |> mutate(
  Estimated_Mean = ((Minimum + 2*IQR1 + 2*Median + 2*IQR3 + Maximum)/8),
  Estimated_SD = (((Maximum - Minimum)/(4*qnorm((n-0.375)/(n+0.25)))) + ((IQR3-IQR1)/(4*qnorm((0.75*n-0.125)/(n+0.25))))),
  Estimated_Variance = (Estimated_SD)^2
)

############################################################

G2007 <- read_excel("G2007.xlsx")
G2007 |> group_by(Group, Days) |> summarise(Mean = mean(Mean_Ethanol_Intake),
                                            SD = sd(Mean_Ethanol_Intake), 
                                            Variance = var(Mean_Ethanol_Intake))

############################################################

Daoura2011 = tibble::tibble(
  "Group" = c("MS0", "MS0", "MS0", "MS0", "MS0",
              "MS15", "MS15", "MS15", "MS15", "MS15",
              "MS360", "MS360", "MS360", "MS360", "MS360"),
  "Week" = c(1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5),
  "Median" = c(1.97, 1.71, 2.08, 2.58, 1.74, 
               1.64, 1.75, 1.73, 1.84, 1.83,
               1.69, 1.90, 1.62, 2.40, 2.72),
  "IQR" = c(1.14, 2.27, 1.83, 2.35, 1.79,
            1.11, 2.42, 1.59, 1.85, 1.49,
            0.58, 1.63, 2.36, 2.14, 1.67),
  "n" = c(15, 15, 15, 15, 15, 
          15, 15, 15, 15, 15,
          14, 14, 14, 14, 14)
)

Daoura2011 = Daoura2011 |> mutate(
  "IQR1" = Median - (IQR/2),
  "IQR3" = Median + (IQR/2)
)

# C3 method 
Daoura2011 |>
  mutate(
    Estimated_Mean = ((IQR1+Median+IQR3)/3),
    Estimated_SD = ((IQR3-IQR1)/(2*qnorm((0.75*n-0.125)/(n+0.25)))),
    Estimated_Variance = Estimated_SD^2
  )

############################################################

L2017 <- read_excel("L2017.xlsx") 

L2017 |> select(c(1:22)) |>
  pivot_longer(c(5:22), names_to = "Week", values_to = "Amount") |>
  mutate(Sessions = 3,
         Intake_Session = Amount/Sessions) |>
  group_by(Rearing, Supplier, Week) |>
  summarise(mean = mean(Intake_Session),
            sd = sd(Intake_Session))

diff_supplier = L2017 |> select(c(1:22)) |>
  pivot_longer(c(5:22), names_to = "Week", values_to = "Amount") |>
  mutate(Sessions = 3,
         Intake_Session = Amount/Sessions)

dif = lm(Intake_Session ~ Week*Supplier*Rearing, data = diff_supplier)
summary(dif) # no difference between suppliers and intake of ethanol (I can combine these)


L2017 = L2017 |> select(c(1:22)) |>
  pivot_longer(c(5:22), names_to = "Week", values_to = "Amount") |>
  filter(!is.na(Amount)) |>
  mutate(Sessions = 3,
         Intake_Session = Amount/Sessions) |>
  group_by(Rearing, Week) |>
  summarise(mean = mean(Intake_Session),
            sd = sd(Intake_Session),
            variance = var(Intake_Session))

############################################################

```



```{=tex}
\begin{align*}
y_{it} \sim N(\theta_{it}, \sigma^{2}_{it}) \quad \alpha_i \sim N(0, 100000) \\
\theta_{it} = \alpha_i + \beta_{i} \cdot time_{it} \quad \mu \sim N(0, 100000) \\
\beta_{i} \sim N(\mu, \tau^2) \quad \tau \sim N(0, 100), \: \tau >0
\end{align*}
```



$y_{it} =$ observed effect at time-point t in study i  
$\sigma^2_{it} =$ is the variance of $y_{it}$  
$\theta_{it} =$ is the true effect at time point t in study i  
$\alpha_i \: and \: \beta_i =$ respectively, the intercept and slope for the study-specific linear regression slope   
$time_{it} =$ the time-point in study i at time t  
$\mu =$ overall trend  
$\tau^2 =$ is the variance in trend between studies  



Comasco et al., 2015: weeks 1-5 (increasing)   
Daoura et al., 2011: weeks 1-5 (not increasing)  
Gustafsson et al., 2007: days 1-18, 19-36, 37-54 (not increasing)   
Lundberg et al., 2017: weeks 1-20 (increasing)  
Oreland et al., 2011: week 3-7 (increasing)  
Ploj et al., 2003: days 4, 4, 7, 11 (not increasing)  
Gustafsson & Nylander, 2006: days 1-18, 19-36, 37-54 (not increasing)    

# Analaysis 1: 

## Table 1: Groupings for Analysis 1  

```{=latex}
{\tiny
\centering
\begin{tabular}{lllllllll}
\hline
Article & Time-Point 1 & Time-Point 2 & Time-Point 3 & Time-Point 4 & Time-Point 5 & Time-Point 6 & Time-Point 7 \\
\hline
Comasco et al., 2015 & week 1 & week 2 & week 3 & week 4 & week 5 & NA & NA \\
Daoura et al., 2011 & week 1 & week 2 & week 3 & week 4 & week 5 & NA & NA \\
Gustafsson et al., 2007 & NA & days 1-18 & NA & days 19-36 & NA & days 37-54 & NA\\
Lundberg et al., 2017 & week 1 & week 2 & week 3 & week 4 & week 5 & week 6 & week 7 \\
Oreland et al., 2011 & NA & NA & week 3 & week 4 & week 5 & week 6 & week 7 \\
Ploj et al., 2003 & 4 days & 4 days & 7 days & 11 days & NA & NA & NA \\
Gustafsson \& Nylander, 2006 & NA & days 1-18 & NA & days 19-36 & NA & days 37-54 & NA \\
\hline
\end{tabular}}
```

* This analysis groups together both sexes and increasing ethanonl percentage with those that are not increasing.  


time-points = {time-point 1, time-point 2, time-point 3, time-point 4, time-point 5, time-point 6, time-point 7}   
study i = {C2015, D2011, G2007, L2017, O2011, P2003, GN2006}  















